# Generated by Django 2.2.24 on 2021-12-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handovertaskdetail',
            name='object_id',
            field=models.CharField(max_length=68, verbose_name='权限ID'),
        ),
    ]
